#!/bin/bash

# sysinfo_page - A script to produce an HTML file with system information.

##### Constants

HEADING="System Information for $HOSTNAME"
RIGHT_NOW=$(date +"%x %r %z")
TIME_STAMP="Updated on $RIGHT_NOW by $USER"

##### Functions

system_info() {
	echo "<h2>System Release Info</h2>"
	echo "<pre>"
	uptime
	echo "</pre>"
}

show_uptime() {
	echo "<h2>System Uptime</h2>"
	echo "<pre>"
	uptime
	echo "</pre>"
}

drive_space() {
	echo "<h2>Filesystem Space</h2>"
	echo "<pre>"
	df
	echo "</pre>"

}

# only superuser has access to this info
home_space() {
if [ "$(id -u)" = "0" ]; then
	echo "<h2>Home Directory Space per User</h2>"
	echo "<pre>"
	du -s /home/* | sort -nr
	echo "</pre>"
fi

}

write_page()
{
cat <<- _EOF_
	<html>
	 <head>
	   <title> $HEADING </title>
	 </head>
	 
	 <body>
	   <h1> $HEADING </h1>
	   <p>$TIME_STAMP</p>
	   $(system_info)
	   $(show_uptime)
	   $(drive_space)
	   $(home_space)	
	 </body>
 	</html>
_EOF_

}

##### Main

interactive=
filename=~/sysinfo_page.html

while [ "$1" != "" ]; do
    case $1 in
        -f | --file )           shift
                                filename=$1
                                ;;
        -i | --interactive )    interactive=1
                                ;;
        -h | --help )           usage
                                exit
                                ;;
        * )                     usage
                                exit 1
    esac
    shift
done


# Test code to verify command line processing

if [ "$interactive" = "1" ]; then
	response=

    echo -n "Enter name of output file [$filename] > "
    read response
    if [ -n "$response" ]; then
        filename=$response
    fi

    if [ -f $filename ]; then
        echo -n "Output file exists. Overwrite? (y/n) > "
        read response
        if [ "$response" != "y" ]; then
            echo "Exiting program."
            exit 1
        fi
    fi
fi
else
	echo "interactive is off"
fi
echo "output file = $filename"


# Write page (comment out until testing is complete)

# write_page > $filename

